package com.example.teacherkotlinproject.data.local

import androidx.room.Dao
import androidx.room.Database
import androidx.room.RoomDatabase
import com.example.teacherkotlinproject.data.model.Publication


// SQLite
//DB, TABLE

//1 к 1
//1 к многим
//многие к 1
//многие ко многим

//У таблиц есть поля PrimaryKey (autogenerated = true/false)
@Database(entities = [Publication::class], version = 1, exportSchema = false)
abstract class AppDatabase: RoomDatabase() {
    abstract fun instagramDao(): InstagramDao
}
